### PR TITLE
feat: Show Similiar blog posts

### PR DESCRIPTION
**Pull request by linkdotnet**
Adding a feature where 3 related blog posts are shown under the main blog post.
This is done by a new background job that calculates similar blog posts and puts them into a new table.
Those entries are then shown.

image

### CODE REVIEW

**Comment by linkdotnet** [comment]
CC @sa-es-ir

**Comment by sa-es-ir** [comment]
@linkdotnet Thanks for letting me know, it's a cool feature, Because there is a new table added, is there anything I need to consider to update the database with old data?

**Comment by linkdotnet** [comment]
No, it just needs that new table (if you use a SQL Database, you can basically grab the query from the `MIGRATION.md` and add the new entry to your `appsettings.json`).

The similarity matrix is built every time a blog post is published or updated. Therefore, just updating a blog post without editing it will trigger everything.

**Comment by linkdotnet** [comment]
It is `v1` of the Tokenzier and Vectorizer - so results may vary ;)
I will work on improving the nits and bits, but the general structure should stay the same.

**Pull request merged**
